version: '3.3'

#для подключения к БД в поле HOST .env файла должно быть указано db
services:
    db:
      image: sameersbn/postgresql:10-2
      container_name: postgresql_db
      environment:
        PG_PASSWORD: $PG_PASSWORD
      restart: always
      ports:
        - 5432:5432
      networks:
        - tg_bot
      volumes:
        - ./postgres:/var/lib/postgresql

    django:
      container_name: djangoproject
      build:
        context: .
      command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --noreload"
      ports:
        - 8000:8000
      networks:
        - tg_bot
      restart: always
      env_file:
        - ".env"
      depends_on:
        - db

    bot:
      image: "${BOT_IMAGE_NAME:-tg_bot-image}"
      container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
      stop_signal: SIGINT
      build:
        context: .
      working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
      volumes:
        - .:/usr/src/app/${BOT_NAME:-tg_bot}
      command: python3 -m bot
      restart: always
      env_file:
        - ".env"
      networks:
        - tg_bot
      depends_on:
        - db
        - django
networks:
  tg_bot:
    driver: bridge
